"""create merchant aliases table

Revision ID: 1ed0a9a4b747
Revises: 52aa077b2407
Create Date: 2026-07-20 02:10:37.581939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ed0a9a4b747'
down_revision: Union[str, Sequence[str], None] = '52aa077b2407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_aliases', sa.Column('canonical_merchant', sa.String(length=255), nullable=False))
    op.add_column('merchant_aliases', sa.Column('match_type', sa.String(length=50), nullable=True))
    op.add_column('merchant_aliases', sa.Column('priority', sa.Integer(), nullable=True))
    op.alter_column('merchant_aliases', 'alias',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('merchant_aliases', 'source',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_merchant_aliases_category'), table_name='merchant_aliases')
    op.drop_index(op.f('ix_merchant_aliases_normalized_name'), table_name='merchant_aliases')
    op.drop_constraint(op.f('uq_merchant_alias_category'), 'merchant_aliases', type_='unique')
    op.drop_index(op.f('ix_merchant_aliases_alias'), table_name='merchant_aliases')
    op.create_index(op.f('ix_merchant_aliases_alias'), 'merchant_aliases', ['alias'], unique=True)
    op.drop_column('merchant_aliases', 'is_active')
    op.drop_column('merchant_aliases', 'confidence')
    op.drop_column('merchant_aliases', 'created_at')
    op.drop_column('merchant_aliases', 'updated_at')
    op.drop_column('merchant_aliases', 'memo')
    op.drop_column('merchant_aliases', 'normalized_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_aliases', sa.Column('normalized_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('merchant_aliases', sa.Column('memo', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('merchant_aliases', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('merchant_aliases', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('merchant_aliases', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('merchant_aliases', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_merchant_aliases_alias'), table_name='merchant_aliases')
    op.create_index(op.f('ix_merchant_aliases_alias'), 'merchant_aliases', ['alias'], unique=False)
    op.create_unique_constraint(op.f('uq_merchant_alias_category'), 'merchant_aliases', ['alias', 'category'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_merchant_aliases_normalized_name'), 'merchant_aliases', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_merchant_aliases_category'), 'merchant_aliases', ['category'], unique=False)
    op.alter_column('merchant_aliases', 'source',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('merchant_aliases', 'alias',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.drop_column('merchant_aliases', 'priority')
    op.drop_column('merchant_aliases', 'match_type')
    op.drop_column('merchant_aliases', 'canonical_merchant')
    # ### end Alembic commands ###
