"""align benefit tier fields

Revision ID: 52aa077b2407
Revises: e8846dd3869f
Create Date: 2026-07-20 01:58:15.632106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52aa077b2407'
down_revision: Union[str, Sequence[str], None] = 'e8846dd3869f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benefit_tiers', sa.Column('card_benefit_id', sa.Integer(), nullable=False))
    op.add_column('benefit_tiers', sa.Column('required_spending', sa.Integer(), nullable=True))
    op.add_column('benefit_tiers', sa.Column('monthly_limit', sa.Integer(), nullable=True))
    op.add_column('benefit_tiers', sa.Column('extraction_method', sa.String(length=100), nullable=True))
    op.add_column('benefit_tiers', sa.Column('review_required', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_benefit_tiers_card_benefit_id'), 'benefit_tiers', ['card_benefit_id'], unique=False)
    op.drop_constraint(op.f('benefit_tiers_source_benefit_id_fkey'), 'benefit_tiers', type_='foreignkey')
    op.create_foreign_key(None, 'benefit_tiers', 'card_benefits', ['card_benefit_id'], ['id'], ondelete='CASCADE')
    op.drop_column('benefit_tiers', 'minimum_spending')
    op.drop_column('benefit_tiers', 'data_status')
    op.drop_column('benefit_tiers', 'manual_review_required')
    op.drop_column('benefit_tiers', 'maximum_spending')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benefit_tiers', sa.Column('maximum_spending', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('benefit_tiers', sa.Column('manual_review_required', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('benefit_tiers', sa.Column('data_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('benefit_tiers', sa.Column('minimum_spending', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'benefit_tiers', type_='foreignkey')
    op.create_foreign_key(op.f('benefit_tiers_source_benefit_id_fkey'), 'benefit_tiers', 'card_benefits', ['source_benefit_id'], ['source_benefit_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_benefit_tiers_card_benefit_id'), table_name='benefit_tiers')
    op.drop_column('benefit_tiers', 'review_required')
    op.drop_column('benefit_tiers', 'extraction_method')
    op.drop_column('benefit_tiers', 'monthly_limit')
    op.drop_column('benefit_tiers', 'required_spending')
    op.drop_column('benefit_tiers', 'card_benefit_id')
    # ### end Alembic commands ###
