"""add user state tables

Revision ID: 87ca6a1f1d04
Revises: 7c42b14f6e90
Create Date: 2026-07-20 10:42:27.089436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ca6a1f1d04'
down_revision: Union[str, Sequence[str], None] = '7c42b14f6e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('monthly_card_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('usage_month', sa.String(length=7), nullable=False),
    sa.Column('previous_month_spending', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_month_spending', sa.Integer(), server_default='0', nullable=False),
    sa.Column('card_monthly_benefit_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', 'usage_month', name='uq_monthly_card_usage_user_card_month')
    )
    op.create_index(op.f('ix_monthly_card_usage_card_id'), 'monthly_card_usage', ['card_id'], unique=False)
    op.create_index(op.f('ix_monthly_card_usage_usage_month'), 'monthly_card_usage', ['usage_month'], unique=False)
    op.create_index(op.f('ix_monthly_card_usage_user_id'), 'monthly_card_usage', ['user_id'], unique=False)
    op.create_table('user_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('selected_option_group', sa.String(length=200), nullable=True),
    sa.Column('selected_option_benefit_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_user_cards_user_card')
    )
    op.create_index(op.f('ix_user_cards_card_id'), 'user_cards', ['card_id'], unique=False)
    op.create_index(op.f('ix_user_cards_user_id'), 'user_cards', ['user_id'], unique=False)
    op.create_table('benefit_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('card_benefit_id', sa.Integer(), nullable=False),
    sa.Column('usage_month', sa.String(length=7), nullable=False),
    sa.Column('monthly_used_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('monthly_used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('daily_used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_benefit_id'], ['card_benefits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_benefit_id', 'usage_month', name='uq_benefit_usage_user_benefit_month')
    )
    op.create_index(op.f('ix_benefit_usage_card_benefit_id'), 'benefit_usage', ['card_benefit_id'], unique=False)
    op.create_index(op.f('ix_benefit_usage_card_id'), 'benefit_usage', ['card_id'], unique=False)
    op.create_index(op.f('ix_benefit_usage_usage_month'), 'benefit_usage', ['usage_month'], unique=False)
    op.create_index(op.f('ix_benefit_usage_user_id'), 'benefit_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_benefit_usage_user_id'), table_name='benefit_usage')
    op.drop_index(op.f('ix_benefit_usage_usage_month'), table_name='benefit_usage')
    op.drop_index(op.f('ix_benefit_usage_card_id'), table_name='benefit_usage')
    op.drop_index(op.f('ix_benefit_usage_card_benefit_id'), table_name='benefit_usage')
    op.drop_table('benefit_usage')
    op.drop_index(op.f('ix_user_cards_user_id'), table_name='user_cards')
    op.drop_index(op.f('ix_user_cards_card_id'), table_name='user_cards')
    op.drop_table('user_cards')
    op.drop_index(op.f('ix_monthly_card_usage_user_id'), table_name='monthly_card_usage')
    op.drop_index(op.f('ix_monthly_card_usage_usage_month'), table_name='monthly_card_usage')
    op.drop_index(op.f('ix_monthly_card_usage_card_id'), table_name='monthly_card_usage')
    op.drop_table('monthly_card_usage')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
