"""add benefit tiers

Revision ID: e8846dd3869f
Revises: b731d3d716a1
Create Date: 2026-07-20 01:49:36.031594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8846dd3869f'
down_revision: Union[str, Sequence[str], None] = 'b731d3d716a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefit_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_benefit_id', sa.String(length=50), nullable=False),
    sa.Column('tier_order', sa.Integer(), nullable=True),
    sa.Column('minimum_spending', sa.Integer(), nullable=True),
    sa.Column('maximum_spending', sa.Integer(), nullable=True),
    sa.Column('benefit_value', sa.Float(), nullable=True),
    sa.Column('benefit_unit', sa.String(length=50), nullable=True),
    sa.Column('data_status', sa.String(length=100), nullable=True),
    sa.Column('manual_review_required', sa.Boolean(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_benefit_id'], ['card_benefits.source_benefit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefit_tiers_source_benefit_id'), 'benefit_tiers', ['source_benefit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_benefit_tiers_source_benefit_id'), table_name='benefit_tiers')
    op.drop_table('benefit_tiers')
    # ### end Alembic commands ###
